name: MLFinal
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11

  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - tqdm
  - jupyter
  - ipykernel
  - optuna

  - catboost
  - xgboost
  - lightgbm
  - imbalanced-learn

  # --- Astronomical Computations ---
  - astropy
  - sncosmo
  - extinction

  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4

  - kaggle
  - pip